name: Python Application
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
      - run: pip install -r requirements-dev.txt
      - name: Runner Flake8
      - run: flake8
