name: Python Application
on: [pull_request]
jobs:
  build:
    steps:
      - name: Install dependencies
      - run: pip install -r requirements-dev.txt
      - name: Runner Flake8
      - run: flake8
